version: "2"

run:
  timeout: 5m

  exclusions:
  generated: lax
  presets:
    - comments
    - common-false-positives
    - std-error-handling
  paths:
    - third_party$
    - builtin$
    - examples$
  
formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - crm2

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
