services:
  anon3anon:
    container_name: anon3anon
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ANON3ANON_DATABASE_PATH: /data/anon3anon.db
    volumes:
      - "./bin:/app/bin"
      - "anon3anon-data:/data"

volumes:
  anon3anon-data:
