[tools]
go = "1.26"
golangci-lint = "2.12.2"

[env]
GOOS = "linux"
GOARCH = "amd64"
CGO_ENABLED = "0"

[tasks.default]
run = [
    { task = "modules" },
    { task = "build" },
    { task = "check" },
]

[tasks.modules]
run = "go mod tidy"

[tasks.build]
run = "go build -trimpath -v --gcflags 'all=-N -l' -o ./bin/anon3anon ./cmd/anon3anon"

[tasks.check]
depends = [ "check:*" ]

[tasks."check:test"]
run = "go test ./..."

[tasks."check:lint"]
run = "golangci-lint run"
