apiVersion: v1
kind: ConfigMap
metadata:
  name: anon3anon-config
data:
  ANON3ANON_RATE_LIMIT_WINDOW: "1h"
  ANON3ANON_RATE_LIMIT_MAX: "100"
  ANON3ANON_LOG_LEVEL: "info"
  ANON3ANON_RETENTION_AGE: "720h"
  ANON3ANON_RETENTION_SWEEP_INTERVAL: "1h"
