apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anon3anon

resources:
  - ../base

generators:
  - secret-generator.yaml

images:
  - name: ghcr.io/nightnoryu/anon3anon
    newTag: 0.1.0
