apiVersion: v1
kind: Secret
metadata:
    name: anon3anon-secrets
    namespace: anon3anon
type: Opaque
stringData:
    ANON3ANON_TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:Nk0H2YhqsTR0SqFRXv4roYj4AFNqw1cdSbxcYZ34O1AAWDVu0DQ5rF2lW0/9OA==,iv:6DexmBBtrHi/fTJiIveo/Ls+kc2e8j+Xu32leH3iuJ8=,tag:TPimxItya3Nlxfawb0vBwQ==,type:str]
    ANON3ANON_ALLOWED_USER_IDS: ""
    ANON3ANON_PSEUDONYM_KEY: ENC[AES256_GCM,data:WZFYU5iPHivl4HiJnKqRqvBXqw+jnOJJIXzhi2Q1k3pYHN90fUcVW8zQtAc=,iv:FfxG45We/FLLe4c7t0TJPxSnJ+6HMpsZ7SEC/SvHVr4=,tag:Sxxd9f2Vn4ZlN4YirmILOw==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVEt6VWc0V0VYM3JoRTY3
            V3p5cUJYb0xsYkZDMDNKMkVobjJVSlpNWG1vCktheXFSY3JCT24xaFFRY3JlczZa
            V0R1NGlQQnA1UmNUMUN0TXpoQjNTTXMKLS0tIHB6MlZMcURGemtOU2Y2Uk5LdW5p
            VWNlN3kxWlN3NUJGUmdiRUQxRHp0REkKxVObSLgBfY5MZY9ndld9CfoeXq/sIzIY
            V7CmSCOxK4ZTZLc+qFfJBgvd4uGs+Gh/P61VqoLOuydO51cVf1kdQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T15:25:42Z"
    mac: ENC[AES256_GCM,data:DGdntu6c0wc8PXpaUl/KDy/9ZC+6eYK7A7szcemv9XTtno9uVjPiilsAnDZpLWvVip6RZAPtQLimd5SXezbY052l8YN1ZX6K+am0PNRVZkG9LoSlvkv1XhPn/8/4XzV33nvtA/m7S0Y7Q9haUgOe7y5YUFSzgGqHdER2ep6xN38=,iv:C50/ELkODtVAa5j6KQ6T2qKihYKQBbMnxU1/77wixdA=,tag:1rwSiqANPN7VpmBfmXMfwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
