apiVersion: v1
kind: Secret
metadata:
    name: anon3anon-secrets
    namespace: anon3anon
type: Opaque
stringData:
    ANON3ANON_TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:+1Bnu1DD65jaeRSuu3FmcInBy1nG5sB8cDRYofxmd/QTTdXkHtmpNJ+RursvwQ==,iv:t5uzTlHjhleb7bE5zhFwPLRKgskGiZH7qJEO/XFMcQE=,tag:R0uVevf5As2VGNdjpFaZEA==,type:str]
    ANON3ANON_ALLOWED_USER_IDS: ""
    ANON3ANON_PSEUDONYM_KEY: ENC[AES256_GCM,data:eMpQyCpDl7/AJGkfWUTqD9BsQx8IURmCkXOW88Vpgjq7I1jaoBwBb8q+j0o=,iv:FpZ+uMKs1hpdnPGSeROSmUnq3fdddKW5vRL/Fp+jCAk=,tag:fto9eTGWkhPoq7/OQP1IGQ==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVEt6VWc0V0VYM3JoRTY3
            V3p5cUJYb0xsYkZDMDNKMkVobjJVSlpNWG1vCktheXFSY3JCT24xaFFRY3JlczZa
            V0R1NGlQQnA1UmNUMUN0TXpoQjNTTXMKLS0tIHB6MlZMcURGemtOU2Y2Uk5LdW5p
            VWNlN3kxWlN3NUJGUmdiRUQxRHp0REkKxVObSLgBfY5MZY9ndld9CfoeXq/sIzIY
            V7CmSCOxK4ZTZLc+qFfJBgvd4uGs+Gh/P61VqoLOuydO51cVf1kdQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T16:25:02Z"
    mac: ENC[AES256_GCM,data:MjQadSXpS/XnbahUbftxBIcIK0EKJ7BmjcY9a2IsNiZ/9//EwftSAxY2sJ3d+Vsd0+KU4ssIbMGb9lCUAfVT5NFeH/TI72VM76zLvOIGKOS+hCLxZZQY/b9g96IMU8qH/IHXBdPvnG4JT/w2m/0s6a/r+SpePOaa2LggdjPi0Ck=,iv:0vxaf6e1g7AgFe0yTW5+ZKm6/PKgjtYMe11xwJEhCis=,tag:6jW8Q3/MlRPcTYxPIM7ZrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
