FROM golang:1.22.5 AS build

WORKDIR /app

COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/anon3anon ./cmd/anon3anon

FROM alpine:latest AS run

COPY --from=build /app/bin/anon3anon /app/bin/

CMD ["/app/bin/anon3anon"]
