apiVersion: apps/v1
kind: Deployment
metadata:
  name: anon3anon
  namespace: anon3anon
  labels:
    app: anon3anon
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: anon3anon
  template:
    metadata:
      labels:
        app: anon3anon
    spec:
      containers:
        - name: anon3anon
          image: ghcr.io/nightnoryu/anon3anon:latest
          imagePullPolicy: Always
          env:
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  name: anon3anon-config
                  key: HTTP_PROXY
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  name: anon3anon-config
                  key: HTTPS_PROXY
            - name: ALL_PROXY
              valueFrom:
                configMapKeyRef:
                  name: anon3anon-config
                  key: ALL_PROXY
            - name: ANON3ANON_TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: anon3anon-secrets
                  key: ANON3ANON_TELEGRAM_BOT_TOKEN
            - name: ANON3ANON_OWNER_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: anon3anon-secrets
                  key: ANON3ANON_OWNER_CHAT_ID
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 64Mi
        - name: warp-proxy
          image: seiry/cloudflare-warp-proxy:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 64Mi
