apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anon3anon-data
  namespace: anon3anon
  labels:
    app: anon3anon
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
