name: Check Go code

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Build
        run: mise run

      - name: Run tests
        run: go test ./...
